### ISSUE TITLE
Back camera stays black

### ISSUE THREAD

**Issue by relioti** [mickaelmendes50/android_device_xiaomi_lmi#7]
Back camera is not available.
Front Camera (pop up) is working as expected

Tested with clean install Paranoid Android Uvite - Unofficial 2
Device K30 Pro Zoom edition

On Paranoid Android Uvite - Unofficial 1 back camera worked as expected

**Comment by mickaelmendes50** [comment]
Thank you for sharing the feedback! 
Looks like I'll need to reimport the lmi camera driver to get lmipro back camera working.

Once done, can you help with testing? Please contact me on Telegram https://t.me/mickaelmendes50

**Comment by relioti** [comment]
> Once done, can you help with testing? Please contact me on Telegram https://t.me/mickaelmendes50

Yes, sure. I wrote you on Telegram

**Comment by relioti** [comment]
With the new Kernel and DTBO Back camera for K30 Pro zoom works as expected. This issue is resolved

**Comment by mickaelmendes50** [comment]
Fixed with following patches:

https://gerrit.aospa.co/c/AOSPA/android_kernel_xiaomi_sm8250/+/37792
https://gerrit.aospa.co/c/AOSPA/android_kernel_xiaomi_sm8250/+/37793
https://gerrit.aospa.co/c/AOSPA/android_kernel_xiaomi_sm8250/+/37794
